Data Analysis

In [69]:
import numpy as np
import pandas as pd
df=pd.read_csv('data_gpr_export.csv')
df.head(5)
df.isna()
year_series=pd.to_datetime(df['month'], format="%m/%d/%Y").dt.year
year_series.name='Year'
month_series=pd.to_datetime(df['month'], format="%m/%d/%Y").dt.month
month_series.name='Month'
df=pd.concat([df, year_series], axis=1)
pd.set_option('display.max_columns', None)
df.columns.tolist()

df=df.rename(columns={'month': 'observation_date'})

In [88]:
df1=pd.read_csv('data_gpr_export.csv')

In [ ]:
df2=pd.read_csv('FEDFUNDS.csv')

# df2['observation_date']=df2['observation_date'].apply(lambda x: '/'.join([x.split('-')[1], x.split('-')[2], x.split('-')[0]]))
# pd.merge(df, df2, on='observation_date', how='left')

    observation_date  FEDFUNDS
0         1954-07-01      0.80
1         1954-08-01      1.22
2         1954-09-01      1.07
3         1954-10-01      0.85
4         1954-11-01      0.83
..               ...       ...
851       2025-06-01      4.33
852       2025-07-01      4.33
853       2025-08-01      4.33
854       2025-09-01      4.22
855       2025-10-01      4.09

[856 rows x 2 columns]

In [78]:
df3=pd.read_csv('UNRATE.csv')
df3

    observation_date  UNRATE
0         1948-01-01     3.4
1         1948-02-01     3.8
2         1948-03-01     4.0
3         1948-04-01     3.9
4         1948-05-01     3.5
..               ...     ...
927       2025-04-01     4.2
928       2025-05-01     4.2
929       2025-06-01     4.1
930       2025-07-01     4.2
931       2025-08-01     4.3

[932 rows x 2 columns]

In [79]:
df4=pd.read_csv('VIXCLS.csv')
df4

     observation_date  VIXCLS
0          1990-01-02   17.24
1          1990-01-03   18.19
2          1990-01-04   19.22
3          1990-01-05   20.11
4          1990-01-08   20.26
...               ...     ...
9350       2025-11-04   19.00
9351       2025-11-05   18.01
9352       2025-11-06   19.50
9353       2025-11-07   19.08
9354       2025-11-10   17.60

[9355 rows x 2 columns]

In [ ]:
gpr_df_raw = pd.read_csv("data_gpr_export.csv")
gpr_df_raw['Date'] = pd.to_datetime(gpr_df_raw['month'])
gpr_df_raw['date_month'] = gpr_df_raw['Date'].dt.strftime('%Y.%m')
us_gpr_df = gpr_df_raw[['date_month','GPRC_USA']]

     date_month  GPRC_USA
0       1899.12       NaN
1       1900.01       NaN
2       1900.03       NaN
3       1900.04       NaN
4       1900.05       NaN
...         ...       ...
1505    2025.06  5.592269
1506    2025.07  3.250141
1507    2025.08  3.521580
1508    2025.09  3.195275
1509    2025.10  3.809381

[1510 rows x 2 columns]

:

In [82]:
df5=pd.read_csv('CPIAUCSL.csv')
df5

    observation_date  CPIAUCSL
0         1947-01-01    21.480
1         1947-02-01    21.620
2         1947-03-01    22.000
3         1947-04-01    22.000
4         1947-05-01    21.950
..               ...       ...
940       2025-05-01   320.580
941       2025-06-01   321.500
942       2025-07-01   322.132
943       2025-08-01   323.364
944       2025-09-01   324.368

[945 rows x 2 columns]

In [83]:
df6=pd.read_csv('sp500adj.csv')
df6

            Date    Value
0     12/31/1927   329.27
1     01/31/1928   327.60
2     02/29/1928   325.58
3     03/31/1928   363.68
4     04/30/1928   372.55
...          ...      ...
1171  07/31/2025  6329.83
1172  08/29/2025  6432.04
1173  09/30/2025  6642.35
1174  10/31/2025  6829.89
1175  11/03/2025  6851.97

[1176 rows x 2 columns]

In [ ]:
df_ult=pd.merge(df2, df3, on='observation_date', how='left')
df_ult=pd.merge(df_ult, df4, on='observation_date', how='left')
df_ult=pd.merge(df_ult, df5, on='observation_date', how='left')

5.8

In [ ]:
df_ult=

    observation_date  FEDFUNDS  UNRATE  VIXCLS  CPIAUCSL
0         1954-07-01      0.80     5.8     NaN    26.860
1         1954-08-01      1.22     6.0     NaN    26.850
2         1954-09-01      1.07     6.1     NaN    26.810
3         1954-10-01      0.85     5.7     NaN    26.720
4         1954-11-01      0.83     5.3     NaN    26.780
..               ...       ...     ...     ...       ...
851       2025-06-01      4.33     4.1     NaN   321.500
852       2025-07-01      4.33     4.2   16.83   322.132
853       2025-08-01      4.33     4.3   20.38   323.364
854       2025-09-01      4.22     NaN   16.12   324.368
855       2025-10-01      4.09     NaN   16.29       NaN

[856 rows x 5 columns]